package com.string;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2015-12-30T17:48:18.426+05:30
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "StringReverseService", 
                  wsdlLocation = "file:/D:/chinna-BizRuntime/workspace/CXFPro/StringTest/wsdl/stringreverse.wsdl",
                  targetNamespace = "http://string.com/") 
public class StringReverseService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://string.com/", "StringReverseService");
    public final static QName StringReversePort = new QName("http://string.com/", "StringReversePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/chinna-BizRuntime/workspace/CXFPro/StringTest/wsdl/stringreverse.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StringReverseService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/chinna-BizRuntime/workspace/CXFPro/StringTest/wsdl/stringreverse.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StringReverseService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StringReverseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StringReverseService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StringReverseService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StringReverseService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StringReverseService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns StringReverse
     */
    @WebEndpoint(name = "StringReversePort")
    public StringReverse getStringReversePort() {
        return super.getPort(StringReversePort, StringReverse.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StringReverse
     */
    @WebEndpoint(name = "StringReversePort")
    public StringReverse getStringReversePort(WebServiceFeature... features) {
        return super.getPort(StringReversePort, StringReverse.class, features);
    }

}
