/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2016-02-02 11:18:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registerform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Registration</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("fieldset.scheduler-border {\n");
      out.write("\tborder: 1px groove #ddd;\n");
      out.write("\tpadding: 0 1.4em 1.4em 1.4em;\n");
      out.write("\tmargin: 0 0 1.5em 0;\n");
      out.write("\t-webkit-box-shadow: 0px 0px 0px 0px #000;\n");
      out.write("\tbox-shadow: 0px 0px 0px 0px #000;\n");
      out.write("\tmargin: 0 0 1.5em 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("legend.scheduler-border {\n");
      out.write("\twidth: inherit;\n");
      out.write("\tpadding: 0 10px;\n");
      out.write("\tborder-bottom: none;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div class=\"container\"\n");
      out.write("\t\tstyle=\"width: 100%; height: 1000px; border: 5px black solid\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<legend>\n");
      out.write("\t\t\t\t<h1>\n");
      out.write("\t\t\t\t\t<center>Registration Form</center>\n");
      out.write("\t\t\t\t</h1>\n");
      out.write("\t\t\t</legend>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"row well\">\n");
      out.write("\t\t\t<form role=\"form\" action=\"\">\n");
      out.write("\t\t\t\t<fieldset class=\"scheduler-border\">\n");
      out.write("\t\t\t\t\t<legend class=\"scheduler-border\">Personal Details</legend>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group row col-xs-12\">\n");
      out.write("\t\t\t\t\t\t<label for=\"rnumber\" class=\"col-sm-3 form-control-label\">Registration\n");
      out.write("\t\t\t\t\t\t\tNumber </label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-2\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"rnumber\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-2\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"btn btn-default btn-xs\">genarate</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group row col-xs-6\">\n");
      out.write("\t\t\t\t\t\t<label for=\"fname\" class=\"col-sm-6 form-control-label\">First\n");
      out.write("\t\t\t\t\t\t\tName </label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"fname\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"First Name\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group row col-xs-6\">\n");
      out.write("\t\t\t\t\t\t<label for=\"lname\" class=\"col-sm-6 form-control-label\">Last\n");
      out.write("\t\t\t\t\t\t\tName</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"lname\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Last Name\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group row col-xs-6\">\n");
      out.write("\t\t\t\t\t\t<label for=\"mname\" class=\"col-sm-6 form-control-label\">Middle\n");
      out.write("\t\t\t\t\t\t\tName</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"mname\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Middle Name\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group row col-xs-6\">\n");
      out.write("\t\t\t\t\t\t<label for=\"dob\" class=\"col-sm-6 form-control-label\">Date\n");
      out.write("\t\t\t\t\t\t\tOf Birth</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"dob\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Date Of Birth\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group row col-xs-6\">\n");
      out.write("\t\t\t\t\t\t<label for=\"uid\" class=\"col-sm-6 form-control-label\">Unique\n");
      out.write("\t\t\t\t\t\t\tId</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"uid\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Unique Id\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group row col-xs-6\">\n");
      out.write("\t\t\t\t\t\t<label for=\"pan\" class=\"col-sm-6 form-control-label\">PAN\n");
      out.write("\t\t\t\t\t\t\tNumber</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"pan\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"PAN Number\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group row col-xs-6\">\n");
      out.write("\t\t\t\t\t\t<label for=\"gender\" class=\"col-sm-6 form-control-label\">Gender</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<label> <input type=\"radio\" name=\"gender\" id=\"male\"\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"option1\"> Male\n");
      out.write("\t\t\t\t\t\t\t</label> <label> <input type=\"radio\" name=\"gender\" id=\"female\"\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"option2\"> Female\n");
      out.write("\t\t\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group row col-xs-6\">\n");
      out.write("\t\t\t\t\t\t<label for=\"status\" class=\"col-sm-6 form-control-label\">Marital\n");
      out.write("\t\t\t\t\t\t\tStatus</label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t<select class=\"form-control\" id=\"sel1\">\n");
      out.write("\t\t\t\t\t\t\t\t<option>Single</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option>Married</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option>Separated</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option>Divorced</option>\n");
      out.write("\t\t\t\t\t\t\t\t<option>Widowed</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group row col-xs-12\">\n");
      out.write("\t\t\t\t\t\t<label for=\"caddress\" class=\"col-sm-3 form-control-label\">Communication\n");
      out.write("\t\t\t\t\t\t\tAddress </label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\">\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"3\" id=\"caddress\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 735px\"></textarea>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group row col-xs-12\">\n");
      out.write("\t\t\t\t\t\t<label class=\"col-sm-3 form-control-label\"> </label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\"> Same as Communication Address\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group row col-xs-12\">\n");
      out.write("\t\t\t\t\t\t<label for=\"paddress\" class=\"col-sm-3 form-control-label\">Parmanent\n");
      out.write("\t\t\t\t\t\t\tAddress </label>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-8\">\n");
      out.write("\t\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"3\" id=\"paddress\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 735px\"></textarea>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</fieldset>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"row well\">\n");
      out.write("\t\t\t<form action=\"\">\n");
      out.write("\t\t\t\t<fieldset class=\"scheduler-border\">\n");
      out.write("\t\t\t\t\t<legend class=\"scheduler-border\">Education Details</legend>\n");
      out.write("\t\t\t\t\t<table class=\"table\">\n");
      out.write("\t\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td>Course</td>\n");
      out.write("\t\t\t\t\t\t\t\t<td>University/College</td>\n");
      out.write("\t\t\t\t\t\t\t\t<td>Year of pass</td>\n");
      out.write("\t\t\t\t\t\t\t\t<td>Percentage</td>\n");
      out.write("\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-sm\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-plus\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"course\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"college\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"yop\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"percentage\"> <span>%</span>\n");
      out.write("\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-sm\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-minus\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"course\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"college\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"yop\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"percentage\"> <span>%</span>\n");
      out.write("\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-sm\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-minus\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t</fieldset>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
